//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace Glass.DBWS {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GPoint", Namespace="http://tempuri.org/")]
    public partial class GPoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string IDField;
        
        private decimal XField;
        
        private decimal YField;
        
        private string UNITField;
        
        private string ZONEField;
        
        private System.DateTime PDATEField;
        
        private decimal VALUE1Field;
        
        private decimal VALUE2Field;
        
        private decimal VALUE3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UNIT {
            get {
                return this.UNITField;
            }
            set {
                if ((object.ReferenceEquals(this.UNITField, value) != true)) {
                    this.UNITField = value;
                    this.RaisePropertyChanged("UNIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ZONE {
            get {
                return this.ZONEField;
            }
            set {
                if ((object.ReferenceEquals(this.ZONEField, value) != true)) {
                    this.ZONEField = value;
                    this.RaisePropertyChanged("ZONE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime PDATE {
            get {
                return this.PDATEField;
            }
            set {
                if ((this.PDATEField.Equals(value) != true)) {
                    this.PDATEField = value;
                    this.RaisePropertyChanged("PDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal VALUE1 {
            get {
                return this.VALUE1Field;
            }
            set {
                if ((this.VALUE1Field.Equals(value) != true)) {
                    this.VALUE1Field = value;
                    this.RaisePropertyChanged("VALUE1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal VALUE2 {
            get {
                return this.VALUE2Field;
            }
            set {
                if ((this.VALUE2Field.Equals(value) != true)) {
                    this.VALUE2Field = value;
                    this.RaisePropertyChanged("VALUE2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal VALUE3 {
            get {
                return this.VALUE3Field;
            }
            set {
                if ((this.VALUE3Field.Equals(value) != true)) {
                    this.VALUE3Field = value;
                    this.RaisePropertyChanged("VALUE3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GResources", Namespace="http://tempuri.org/")]
    public partial class GResources : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IDField;
        
        private decimal XField;
        
        private decimal YField;
        
        private string NAMEField;
        
        private int TYPEField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int TYPE {
            get {
                return this.TYPEField;
            }
            set {
                if ((this.TYPEField.Equals(value) != true)) {
                    this.TYPEField = value;
                    this.RaisePropertyChanged("TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBWS.DBServiceSoap")]
    public interface DBServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetPoints", ReplyAction="*")]
        System.IAsyncResult BeginGetPoints(Glass.DBWS.GetPointsRequest request, System.AsyncCallback callback, object asyncState);
        
        Glass.DBWS.GetPointsResponse EndGetPoints(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetResources", ReplyAction="*")]
        System.IAsyncResult BeginGetResources(Glass.DBWS.GetResourcesRequest request, System.AsyncCallback callback, object asyncState);
        
        Glass.DBWS.GetResourcesResponse EndGetResources(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPoints", Namespace="http://tempuri.org/", Order=0)]
        public Glass.DBWS.GetPointsRequestBody Body;
        
        public GetPointsRequest() {
        }
        
        public GetPointsRequest(Glass.DBWS.GetPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPointsRequestBody {
        
        public GetPointsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPointsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Glass.DBWS.GetPointsResponseBody Body;
        
        public GetPointsResponse() {
        }
        
        public GetPointsResponse(Glass.DBWS.GetPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Glass.DBWS.GPoint> GetPointsResult;
        
        public GetPointsResponseBody() {
        }
        
        public GetPointsResponseBody(System.Collections.Generic.List<Glass.DBWS.GPoint> GetPointsResult) {
            this.GetPointsResult = GetPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResourcesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResources", Namespace="http://tempuri.org/", Order=0)]
        public Glass.DBWS.GetResourcesRequestBody Body;
        
        public GetResourcesRequest() {
        }
        
        public GetResourcesRequest(Glass.DBWS.GetResourcesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetResourcesRequestBody {
        
        public GetResourcesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResourcesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResourcesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Glass.DBWS.GetResourcesResponseBody Body;
        
        public GetResourcesResponse() {
        }
        
        public GetResourcesResponse(Glass.DBWS.GetResourcesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetResourcesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Glass.DBWS.GResources> GetResourcesResult;
        
        public GetResourcesResponseBody() {
        }
        
        public GetResourcesResponseBody(System.Collections.Generic.List<Glass.DBWS.GResources> GetResourcesResult) {
            this.GetResourcesResult = GetResourcesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBServiceSoapChannel : Glass.DBWS.DBServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPointsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPointsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Glass.DBWS.GPoint> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Glass.DBWS.GPoint>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetResourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetResourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Glass.DBWS.GResources> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Glass.DBWS.GResources>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceSoapClient : System.ServiceModel.ClientBase<Glass.DBWS.DBServiceSoap>, Glass.DBWS.DBServiceSoap {
        
        private BeginOperationDelegate onBeginGetPointsDelegate;
        
        private EndOperationDelegate onEndGetPointsDelegate;
        
        private System.Threading.SendOrPostCallback onGetPointsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetResourcesDelegate;
        
        private EndOperationDelegate onEndGetResourcesDelegate;
        
        private System.Threading.SendOrPostCallback onGetResourcesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DBServiceSoapClient() {
        }
        
        public DBServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<GetPointsCompletedEventArgs> GetPointsCompleted;
        
        public event System.EventHandler<GetResourcesCompletedEventArgs> GetResourcesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Glass.DBWS.DBServiceSoap.BeginGetPoints(Glass.DBWS.GetPointsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPoints(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetPoints(System.AsyncCallback callback, object asyncState) {
            Glass.DBWS.GetPointsRequest inValue = new Glass.DBWS.GetPointsRequest();
            inValue.Body = new Glass.DBWS.GetPointsRequestBody();
            return ((Glass.DBWS.DBServiceSoap)(this)).BeginGetPoints(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glass.DBWS.GetPointsResponse Glass.DBWS.DBServiceSoap.EndGetPoints(System.IAsyncResult result) {
            return base.Channel.EndGetPoints(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.Generic.List<Glass.DBWS.GPoint> EndGetPoints(System.IAsyncResult result) {
            Glass.DBWS.GetPointsResponse retVal = ((Glass.DBWS.DBServiceSoap)(this)).EndGetPoints(result);
            return retVal.Body.GetPointsResult;
        }
        
        private System.IAsyncResult OnBeginGetPoints(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetPoints(callback, asyncState);
        }
        
        private object[] OnEndGetPoints(System.IAsyncResult result) {
            System.Collections.Generic.List<Glass.DBWS.GPoint> retVal = this.EndGetPoints(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPointsCompleted(object state) {
            if ((this.GetPointsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPointsCompleted(this, new GetPointsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPointsAsync() {
            this.GetPointsAsync(null);
        }
        
        public void GetPointsAsync(object userState) {
            if ((this.onBeginGetPointsDelegate == null)) {
                this.onBeginGetPointsDelegate = new BeginOperationDelegate(this.OnBeginGetPoints);
            }
            if ((this.onEndGetPointsDelegate == null)) {
                this.onEndGetPointsDelegate = new EndOperationDelegate(this.OnEndGetPoints);
            }
            if ((this.onGetPointsCompletedDelegate == null)) {
                this.onGetPointsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPointsCompleted);
            }
            base.InvokeAsync(this.onBeginGetPointsDelegate, null, this.onEndGetPointsDelegate, this.onGetPointsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Glass.DBWS.DBServiceSoap.BeginGetResources(Glass.DBWS.GetResourcesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetResources(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetResources(System.AsyncCallback callback, object asyncState) {
            Glass.DBWS.GetResourcesRequest inValue = new Glass.DBWS.GetResourcesRequest();
            inValue.Body = new Glass.DBWS.GetResourcesRequestBody();
            return ((Glass.DBWS.DBServiceSoap)(this)).BeginGetResources(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Glass.DBWS.GetResourcesResponse Glass.DBWS.DBServiceSoap.EndGetResources(System.IAsyncResult result) {
            return base.Channel.EndGetResources(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.Generic.List<Glass.DBWS.GResources> EndGetResources(System.IAsyncResult result) {
            Glass.DBWS.GetResourcesResponse retVal = ((Glass.DBWS.DBServiceSoap)(this)).EndGetResources(result);
            return retVal.Body.GetResourcesResult;
        }
        
        private System.IAsyncResult OnBeginGetResources(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetResources(callback, asyncState);
        }
        
        private object[] OnEndGetResources(System.IAsyncResult result) {
            System.Collections.Generic.List<Glass.DBWS.GResources> retVal = this.EndGetResources(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetResourcesCompleted(object state) {
            if ((this.GetResourcesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetResourcesCompleted(this, new GetResourcesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetResourcesAsync() {
            this.GetResourcesAsync(null);
        }
        
        public void GetResourcesAsync(object userState) {
            if ((this.onBeginGetResourcesDelegate == null)) {
                this.onBeginGetResourcesDelegate = new BeginOperationDelegate(this.OnBeginGetResources);
            }
            if ((this.onEndGetResourcesDelegate == null)) {
                this.onEndGetResourcesDelegate = new EndOperationDelegate(this.OnEndGetResources);
            }
            if ((this.onGetResourcesCompletedDelegate == null)) {
                this.onGetResourcesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetResourcesCompleted);
            }
            base.InvokeAsync(this.onBeginGetResourcesDelegate, null, this.onEndGetResourcesDelegate, this.onGetResourcesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Glass.DBWS.DBServiceSoap CreateChannel() {
            return new DBServiceSoapClientChannel(this);
        }
        
        private class DBServiceSoapClientChannel : ChannelBase<Glass.DBWS.DBServiceSoap>, Glass.DBWS.DBServiceSoap {
            
            public DBServiceSoapClientChannel(System.ServiceModel.ClientBase<Glass.DBWS.DBServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPoints(Glass.DBWS.GetPointsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetPoints", _args, callback, asyncState);
                return _result;
            }
            
            public Glass.DBWS.GetPointsResponse EndGetPoints(System.IAsyncResult result) {
                object[] _args = new object[0];
                Glass.DBWS.GetPointsResponse _result = ((Glass.DBWS.GetPointsResponse)(base.EndInvoke("GetPoints", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetResources(Glass.DBWS.GetResourcesRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetResources", _args, callback, asyncState);
                return _result;
            }
            
            public Glass.DBWS.GetResourcesResponse EndGetResources(System.IAsyncResult result) {
                object[] _args = new object[0];
                Glass.DBWS.GetResourcesResponse _result = ((Glass.DBWS.GetResourcesResponse)(base.EndInvoke("GetResources", _args, result)));
                return _result;
            }
        }
    }
}
